### ISSUE TITLE
Not a universal solution

### ISSUE THREAD

**Issue by yuchiko** [esperanzzza/telychko-easystartinit-nov16-#1]
Tell me what you will do if I ask you to change orange block's width or height ?
[this project](https://github.com/esperanzzza/telychko-easystartinit-nov16-/blob/master/lesson_00/2.1.2/task-2-1_2-from-the-section-practice-standard-layouts.markdown)

**Comment by esperanzzza** [comment]
Ok, I will make the changes. But as far I understood the task, the point was to find a universal decision for any size of the green box only. And judging by the task and pictures, the orange boxes remain of the same size. But, sure, no problem, I'll send you a new decision.

**Comment by esperanzzza** [comment]
Here is a better solution: https://gist.github.com/esperanzzza/d85e55ca9838aeab2bfce1c5b456bfec

**Comment by yuchiko** [comment]
My fault, sorry. We will change our task description :)
